---
- name: start apache
  sudo: True
  service: name=apache2 state=started

- name: restart apache
  sudo: True
  service: name=apache2 state=restarted

- name: reload apache
  sudo: True
  service: name=apache2 state=reloaded
