---
- name: check if composer is installed
  stat: "path={{ composer_path }}"
  register: composer_bin
  tags: composer

- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists
  tags: composer

- name: install composer
  command: >
    php composer-installer.php
    chdir=/tmp
  when: not composer_bin.stat.exists
  tags: composer

- name: rename composer.phar to composer
  become: yes
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
  tags: composer

- name: make composer executable
  file: path=/usr/local/bin/composer mode=a+x state=file
  tags: composer

- name: Add GitHub OAuth token for Composer (if configured).
  template:
    src: "auth.json.j2"
    dest: "{{ composer_home_path }}/auth.json"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"
  when: composer_github_oauth_token != ''
